### ISSUE TITLE
Pro version: No way to make truly full screen?

### ISSUE THREAD

**Issue by jamesautodude** [wire-elements/modal#482]
I'm having an issue where making a modal fullscreen doesn't make it fullscreen 

This is on bootstrap version 

I changed the config to be fullscreen and while it does make it fullscreen if the model has enough info in it, it doesn't make it fullscreen for cases with minimal info (like one word in the body of the modal), instead it shrinks the modal header down to the bottom of the screen

Is there a way to force the header to stay at the top of the view no matter how much content is in the body?

**Comment by PhiloNL** [comment]
Hi James,

I think it should work when using:

```php
    public static function attributes(): array
    {
        return [
            'size' => 'fullscreen',
        ];
    }
```

This will add an additional CSS selector to the modal with the following CSS:

```css
.wep-modal-content.wep-modal-content-fullscreen {
    height: 100vh;
    border-radius: 0;
    box-shadow: none;
    margin: 0px;
    width: 100%;
}
```

Maybe you can tweak the CSS a little using the `.wep-modal-content-fullscreen` selector.
