### ISSUE TITLE
Pro version: bootstrap styling is not applied

### ISSUE THREAD

**Issue by drSun** [wire-elements/modal#498]
Hi, I bought wire elements pro, and I use bootstrap theme https://techzaa.in/velex/ui-modal.html

I made everything according to docs, but modal and slideover styling simply doesn't work. Please look at demo page http://test.sita-rama.ru/articles

All vendors are loaded nicely, incl overlay style for bootstrap. First green button launches normal modal, and other 2 buttons launch wrongly styled modal and slideover. I tried to put native modal html from theme, but it also doesn't work, only some elements like buttons etc look nice, not modal itself.

In the demo I put next html (one button is styled properly, but even content-padding doesn't work):

![Image](https://github.com/user-attachments/assets/33dad536-f652-4323-b92f-9be9433db544)

What can be done in this regard?

**Comment by drSun** [comment]
Just found another bug - for SlideOver component it renders tailwind slide-over.blade.php, but it's set bootstrap in config.

**Comment by PhiloNL** [comment]
Hi there! Thanks for your purchase. Which version of bootstrap are you using?

**Comment by drSun** [comment]
Hi

Bootstrap  v5.3.3

**Comment by PhiloNL** [comment]
Hi,

It looks like the issue is caused by changes in Bootstrap. For time being, the following should work. Add the following CSS to your app:

```css
.wep-modal-content {
    --bs-modal-zindex: 1055;
    --bs-modal-width: 500px;
    --bs-modal-padding: 1.25rem;
    --bs-modal-margin: .5rem;
    --bs-modal-color: ;
    --bs-modal-bg: var(--bs-secondary-bg);
    --bs-modal-border-color: transparent;
    --bs-modal-border-width: var(--bs-border-width);
    --bs-modal-border-radius: var(--bs-border-radius-lg);
    --bs-modal-box-shadow: 0 .125rem .25rem rgba(0, 0, 0, .075);
    --bs-modal-inner-border-radius: calc(var(--bs-border-radius-lg) -(var(--bs-border-width)));
    --bs-modal-header-padding-x: 1.25rem;
    --bs-modal-header-padding-y: 1.25rem;
    --bs-modal-header-padding: 1.25rem 1.25rem;
    --bs-modal-header-border-color: var(--bs-border-color);
    --bs-modal-header-border-width: var(--bs-border-width);
    --bs-modal-title-line-height: 1.5;
    --bs-modal-footer-gap: .5rem;
    --bs-modal-footer-bg: ;
    --bs-modal-footer-border-color: var(--bs-border-color);
    --bs-modal-footer-border-width: var(--bs-border-width);
}
```

**Comment by drSun** [comment]
Hi @PhiloNL 
Thanks for fixing modal, it works pretty nice!

May you kindly provide the same for SlideOver? Because it's still broken. Thank you so much.

**Comment by PhiloNL** [comment]
```css
.wep-slide-over-container {
    --bs-offcanvas-zindex: 1045;
    --bs-offcanvas-width: 280px;
    --bs-offcanvas-height: 30vh;
    --bs-offcanvas-padding-x: 1.25rem;
    --bs-offcanvas-padding-y: 1.25rem;
    --bs-offcanvas-color: var(--bs-body-color);
    --bs-offcanvas-bg: var(--bs-secondary-bg);
    --bs-offcanvas-border-width: var(--bs-border-width);
    --bs-offcanvas-border-color: transparent;
    --bs-offcanvas-box-shadow: 0 .125rem .25rem rgba(0, 0, 0, .075);
    --bs-offcanvas-transition: transform .3s ease-in-out;
    --bs-offcanvas-title-line-height: 1.5;
}
```
